name: Cleanup Old Actions

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old workflow runs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              per_page: 100
            });

            // Keep only the last 20 runs
            const runsToDelete = runs.data.workflow_runs
              .sort((a, b) => new Date(b.created_at) - new Date(a.created_at))
              .slice(20);

            for (const run of runsToDelete) {
              console.log(`Deleting run #${run.id} created at ${run.created_at}`);
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }
