name: Build J2ME Application

on:
  push:
    branches: [ j2me ]
  pull_request:
    branches: [ j2me ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./j2me  # do our stuff in the j2me source directory
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
    
    - name: Download J2ME Libraries
      run: |
        mkdir -p ~/wtk/lib
        cd ~/wtk/lib
        
        # Download MicroEmulator libraries (these contain the MIDP/CLDC APIs)
        wget -O midpapi20.jar https://repo1.maven.org/maven2/org/microemu/microemu-midp/2.0.4/microemu-midp-2.0.4.jar
        wget -O cldcapi11.jar https://repo1.maven.org/maven2/org/microemu/microemu-cldc/2.0.4/microemu-cldc-2.0.4.jar
        
        echo "Downloaded libraries:"
        ls -lh
        
        # Create bin directory with dummy preverify
        mkdir -p ~/wtk/bin
        cat > ~/wtk/bin/preverify << 'EOF'
        #!/bin/bash
        # Simple preverify that just copies files
        while [[ $# -gt 0 ]]; do
          case $1 in
            -d)
              DEST="$2"
              shift 2
              ;;
            -classpath)
              shift 2
              ;;
            *)
              SOURCE="$1"
              shift
              ;;
          esac
        done
        
        mkdir -p "$DEST"
        if [ -d "$SOURCE" ]; then
          cp -r "$SOURCE"/* "$DEST/"
        fi
        EOF
        chmod +x ~/wtk/bin/preverify
    
    - name: Verify Libraries
      run: |
        echo "WTK Home contents:"
        ls -R ~/wtk/
        
        echo "Checking JAR contents:"
        jar tf ~/wtk/lib/midpapi20.jar | head -20
        jar tf ~/wtk/lib/cldcapi11.jar | head -20
    
    - name: Create source directory structure
      run: |
        mkdir -p j2me/src
        if [ -f GoogleBallsMIDlet.java ]; then
          cp GoogleBallsMIDlet.java j2me/src/
        fi
        
        if [ ! -f j2me/src/GoogleBallsMIDlet.java ]; then
          echo "ERROR: Source file not found!"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi
    
    - name: Build with Ant
      env:
        WTK_HOME: /home/runner/wtk
      run: |
        cd j2me
        ant clean package
    
    - name: List build artifacts
      run: |
        echo "Build artifacts:"
        ls -lh j2me/dist/
        
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: GoogleBalls-MIDlet
        path: |
          j2me/dist/GoogleBalls.jar
          j2me/dist/GoogleBalls.jad